apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-bookinfo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajilpb/Istio.git
    targetRevision: HEAD
    path: Bookinfo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    name: ratings
    namespace: default
    jqPathExpressions:
    - .spec.http[]?.route[]?.weight
  - group: networking.istio.io
    kind: DestinationRule
    name: ratings
    namespace: default
    jqPathExpressions:
    - .spec.subsets[]?.labels."rollouts-pod-template-hash"
  syncPolicy:
    automated:
      prune: true   
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
